### ISSUE TITLE
IBM Cloud Storage

### ISSUE THREAD

**Issue by andrewgaul** [andrewgaul/object-store-comparison#20]
Allegedly 25% cheaper than AWS:

http://www.dailytech.com/IBM++Cloud+Object+Storage+Cheaper+than+Amazon+S3/article37699.htm

I cannot find an official pricing page in my initial search.

**Comment by matrixik** [comment]
Found it:
https://www.ibm.com/cloud-computing/bluemix/cloud-object-storage
